"../../../3rdparty/bin/protoc" caffe.proto --cpp_out="./"
"../../../3rdparty/bin/protoc" caffe.proto --python_out="./"
mkdir "../../../python/caffe/proto/"
copy nul "../../../python/caffe/proto/__init__.py"
copy caffe_pb2.py "../../../python/caffe/proto/"